# Default resources for snakemake
---
__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1024


set-threads:
    # preprocess
    preprocess__hosts: 8
    preprocess__fastp: 8
    preprocess__bowtie2__build: 24
    preprocess__bowtie2__map: 24
    preprocess__bowtie2__fastq: 24
    preprocess__clean: 24
    preprocess__kraken2__assign: 8
    # assemble
    assemble__megahit: 24
    assemble__megahit__rename: 24
    assemble__megahit__archive: 24
    assemble__bowtie2__build: 24
    assemble__bowtie2__map: 24
    # prokaryotes
    ## prokaryotes - cluster
    prokaryotes__cluster__concoct: 24
    prokaryotes__cluster__maxbin2: 4
    prokaryotes__cluster__metabat2: 24
    prokaryotes__cluster__magscot__prodigal: 24
    prokaryotes__cluster__magscot__hmmsearch_pfam: 4
    prokaryotes__cluster__magscot__hmmsearch_tigr: 4
    prokaryotes__cluster__drep__separate_bins: 24
    prokaryotes__cluster__drep__run: 24
    ## prokaryotes - annotate
    prokaryotes__annotate__checkm2: 24
    prokaryotes__annotate__dram__annotate__archive: 24
    prokaryotes__annotate__gtdbtk__classify_wf: 24
    prokaryotes__annotate__quast: 4
    ## prokaryotes - quantify
    prokaryotes__quantify__bowtie2__index: 24
    prokaryotes__quantify__bowtie2__map: 24
    # viruses
    ## viruses - cluster
    viruses__cluster__genomad: 24
    viruses__cluster__dedupe: 24
    viruses__cluster__mmseqs: 24
    ## viruses - annotate
    viruses__annotate__genomad: 24
    viruses__annotate__virsorter2: 24
    viruses__annotate__dramv__annotate: 24
    viruses__annotate__quast: 4
    ## viruses - quantify
    viruses__quantify__bowtie2__build: 24
    viruses__quantify__bowtie2__map: 24


set-resources:
    # preprocess
    preprocess__fastp:
        mem_mb: 8G
        runtime: 1h
    preprocess__bowtie2__build:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    preprocess__bowtie2__map:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 4h
    preprocess__bowtie2__fastq:
        mem_mb: 8 * 1024
        runtime: 2h
    preprocess__kraken2__assign:
        mem_mb: 500G
        runtime: 1d
    preprocess__nonpareil__run:
        runtime: 6h
    preprocess__singlem__pipe:
        runtime: 2h
        mem_mb: 16G
    preprocess__singlem__condense:
        runtime: 6h
    preprocess__multiqc:
        mem_mb: 4 * 1024 * 2 ** (attempt - 1)
        runtime: 6h

    # assemble
    assemble__megahit:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 1w
    assemble__bowtie2__build:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6h
    assemble__bowtie2__map:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6h
    assemble__quast:
        mem_mb: 8G
    assemble__multiqc:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 6h

    # prokaryotes
    prokaryotes__multiqc:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 6h

    ## prokaryotes - cluster
    prokaryotes__cluster__concoct:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    prokaryotes__cluster__maxbin2:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    prokaryotes__cluster__metabat2:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    prokaryotes__cluster__magscot__prodigal:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    prokaryotes__cluster__magscot__hmmsearch_pfam:
        mem_mb: 8G
        runtime: 1d
    prokaryotes__cluster__magscot__hmmsearch_tigr:
        mem_mb: 8G
        runtime: 1d
    prokaryotes__cluster__magscot__run:
        mem_mb: 8G
        runtime: 12h
    prokaryotes__cluster__magscot__reformat:
        mem_mb: 8G
    prokaryotes__cluster__magscot__rename:
        mem_mb: 8G

    ## prokaryotes - annotate
    prokaryotes__annotate__checkm2:
        mem_mb: 16G
        runtime: 1d
    prokaryotes__annotate__dram__annotate:
        mem_mb: 8G
        runtime: 1d
    prokaryotes__annotate__dram__distill:
        mem_mb: 16G
        runtime: 1d
    prokaryotes__annotate__gtdbtk__classify_wf:
        mem_mb: 128 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    prokaryotes__annotate__drep__dereplicate:
        mem_mb: 4G
        runtime: 6h

    ## prokaryotes - quantify
    prokaryotes__quantify__bowtie2__build:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6h
    prokaryotes__quantify__bowtie2__map:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6d
    prokaryotes__quantify__coverm__genome__aggregate:
        mem_mb: 8G
    prokaryotes__quantify__coverm__contig__aggregate:
        mem_mb: 8G

    # viruses
    viruses__multiqc:
        mem_mb: 8 * 1024 * 2 ** (attempt - 1)
        runtime: 6h

    ## viruses - cluster
    viruses__cluster__genomad:
        mem_mb: 32G

    ## viruses - annotate
    viruses__annotate__genomad:
        mem_mb: 32G
    viruses__annotate__quast:
        mem_mb: 8G

    ## viruses - quantify
    viruses__quantify__bowtie2__build:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    viruses__quantify__bowtie2__map:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    viruses__quantify__coverm__genome__aggregate:
        mem_mb: 8G
    viruses__quantify__coverm__contig_aggregate:
        mem_mb: 8G
