# Paths and parameters relative to references
---
host:
  fasta: resources/reference/chicken_39_sub.fa.gz

singlem:
  data: resources/S3.2.0.GTDB_r214.metapackage_20230428.smpkg.zb

magscot:
  pfam_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_Pfam-A.hmm
  tigr_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_tigrfam.hmm

dram_database: "dram_db"
gtdbtk_database: "../gtdbtk_data.tar.gz"
