# Paths and parameters relative to references
---
hosts:  # Add more in case of multi-host, remove entries in case of environmental sample
  chicken: resources/reference/chicken_39_sub.fa.gz

magscot:
  pfam_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_Pfam-A.hmm.gz
  tigr_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_tigrfam.hmm.gz

databases:
  dram: resources/databases/dram/20230811
  gtdbtk: resources/databases/gtdbtk/release214
  singlem: resources/databases/singlem/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb
  kraken2:  # add entries as necessary
    refseq500: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB
  virify: resources/databases/virify
  checkm2: resources/databases/checkm2/uniref100.KO.1.dmnd
