# Paths and parameters relative to references
---
host:
  fasta: resources/reference/chicken_39_sub.fa.gz

magscot:
  pfam_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_Pfam-A.hmm
  tigr_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_tigrfam.hmm

dram_database: "resources/mock_dram_db"
gtdbtk_database: "resources/mock_gtdbtk_db"
singlem_database: "resources/S3.2.0.GTDB_r214.metapackage_20230428.smpkg.zb_mock"
