# Execution parameters
---
pre:
  fastp:
    length_required: 25  # nonpareil requires at least 25bp
    extra: "--trim_poly_g --trim_poly_x"
  bowtie2-build:
    extra: ""
  bowtie2:
    extra: ""
    samtools:
      mem_per_thread: 1G
  coverm:
    genome:
      methods: "count"
      min_covered_fraction: 0.0
      separator: "^"
    contig:
      methods: "count"

assembly:
  megahit:
    extra: ""
    min_contig_len: 1500
