# Execution parameters
---
preprocess:
  fastp:
    length_required: 25  # nonpareil requires at least 25bp
  bowtie2:  # mem_gb >= mem_host + threads * samtools_mem
    samtools_mem: 1G

assemble:
  megahit:
    min_contig_len: 1500
  samtools:
    mem: 1G

# common both to prokaryotes and viruses
quantify:
  bowtie2:
    samtools_mem: 1G
  coverm:   # https://github.com/wwood/CoverM#calculation-methods
    genome:
      methods: ["count", "covered_bases", "length"]
      min_covered_fraction: 0.0
      separator: "@"
    contig:
      methods: ["count", "covered_bases", "length"]

prokaryotes:
  cluster:
    drep: "--completeness 75 --contamination --25 --P_ani 0.9 --S_ani 0.95"

viral:
  genomad:
    filtering: ""  # nothing, --conservative, or --relaxed
    use_cuda: "export CUDA_VISIBLE_DEVICES=-1"  # in case you have problems with cuda and tensorflow
    extra: "--disable-nn-classification"  # leave empty if you want to use. it is here to disable it for testing
