# Execution parameters
---
pre:
  fastp:
    length_required: 25  # nonpareil requires at least 25bp
    extra: "--trim_poly_g --trim_poly_x"
  bowtie2-build:
    extra: ""
  bowtie2:
    extra: ""
    samtools:
      mem_per_thread: 1G
  coverm:
    genome:
      methods: "count"
      min_covered_fraction: 0.0
      separator: "^"
    contig:
      methods: "count"

assembly:
  megahit:
    extra: ""
    min_contig_len: 1500
  quast:
    extra: ""
  bowtie2-build:
    extra: ""
  bowtie2:
    extra: ""
  samtools:
    mem: 1G

binning:
  metawrap_binning:
    min_length: 1500
    extra: ""
  metawrap_bin_refinement:
    completeness: 50
    contamination: 10
    extra: "--quick"
  quast:
    extra: ""
  bowtie2-build:
    extra: ""
  bowtie2:
    extra: ""
  samtools:
    mem: 1G
