# Execution parameters
---
pre:
  fastp:
    length_required: 25  # nonpareil requires at least 25bp
    extra: "--trim_poly_g --trim_poly_x"
  bowtie2-build:
    extra: ""
    memory_gb: 8
  bowtie2:
    memory_gb: 64
    extra: ""
    samtools:
      mem_per_thread: 1G
  coverm:
    genome:
      methods: ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods
      min_covered_fraction: 0.0
      separator: "^"
    contig:
      methods: ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods
  kraken2:
    memory_gb: 32

assemble:
  megahit:
    extra: ""
    min_contig_len: 1500
    memory_gb: 4
  quast:
    extra: ""
  bowtie2-build:
    extra: ""
    memory_gb: 8
  bowtie2:
    extra: ""
    memory_gb: 8
  samtools:
    mem: 1G
  coverm:
    genome:
      methods:  ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods
      min_covered_fraction: 0.0
      separator: "@"
    contig:
      methods:  ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods

bin:
  quast:
    extra: ""
  bowtie2-build:
    extra: ""
  bowtie2:
    extra: ""
  samtools:
    mem: 1G

dereplicate:
  drep:
    threads: 1  # Careful with pplacer!
    memory_gb: 22  # 22GB * pplacer cores
  bowtie2-build:
    extra: ""
    memory_gb: 8
  bowtie2:
    extra: ""
    memory_gb: 8
  samtools:
    mem: 1G
  coverm:
    genome:
      methods:  ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods
      min_covered_fraction: 0.0
      separator: "@"
    contig:
      methods:  ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods
  quast:
    extra: ""
  gtdbtk:
    memory_gb: 32
  dram:
    memory_gb: 32
