channels:
  - conda-forge
  - bioconda
dependencies:
  - bowtie2 =2.5.3
  - coverm =0.7.0
  - csvkit =1.3.0
  - dram =1.4.6
  - drep =3.4.5
  - parallel =20240122
  - quast =5.2.0
  - r-argparse =2.2.2
  - r-tidyverse =2.0.0
  - samtools =1.19.2
