# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

env:
  CACHE_NUMBER: 0  # Increment this number to invalidate the cache

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:

      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up caches
        uses: actions/cache@v4
        with:
          path: |
            .snakemake/conda
            ~/.cache/pre-commit/
          key: snakemake-conda

      - name: Download All Environments
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            preprocess prokaryotes report
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --conda-create-envs-only

      - name: Clean conda cache
        run: conda clean --all --yes

      - name: Test workflow - Preprocess
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            preprocess__bowtie2
            preprocess__fastp
            preprocess__kraken2
            preprocess__samtools
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5

      - name: Test workflow - Assemble (until megahit)
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            prokaryotes__assemble__megahit
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5

      - name: Test workflow - Assemble (replace mock assembly for something more meaty)
        run: >
          sudo bash -c "cp resources/mock_assembly.fa.gz results/assemble/megahit/all.fa.gz"

      - name: Test workflow - Assemble (from megahit to magscot)
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            prokaryotes__assemble__magscot
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            --rerun-triggers mtime

      - name: Test workflow - Assemble (skip drep)
        run: |
          sudo mkdir --parents results/assemble/drep/dereplicated_genomes
          sudo touch results/assemble/drep/dereplicated_genomes/.snakemake_timestamp
          sudo bash -c "cp resources/mock_assembly.fa.gz results/assemble/drep/dereplicated_genomes/all:bin_00001.fa.gz"

      - name: Test workflow - Quantify (skip drep)
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            prokaryotes__quantify
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            --rerun-triggers mtime

      - name: Test workflow - Annotate (only quast)
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            prokaryotes__annotate__quast
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            --rerun-triggers mtime

      - name: Test workflow - Report
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            report
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            --rerun-triggers mtime

      - name: Delete everything
        run: |
          sudo find results -not -name "*.log" -type f -delete -print

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: results
          path: |
            results/**/*.log
            # results/
            # reports/
            # !**/*.cram
            # !**/*.fq.gz
            # !**/*.bam
            # !**/*.bt2
